### ISSUE TITLE
Oro 4.2 Webpack Compatibility Issue

### ISSUE THREAD

**Issue by chrisaligent** [aligent/braintree-orocommerce#24]
Unable to build JS dependencies in 4.2.X:
![2021-11-09_14-56](https://user-images.githubusercontent.com/45612883/140862044-bae5cb11-201c-4852-b6e7-a9d7bf74a08d.png)

Have traced it down to the following 4.2 Change:
https://github.com/oroinc/platform/blob/4.2.6/CHANGELOG.md#webpack-config-builder

In theory it should be a matter of adjusting:
`vendor/aligent/braintree-orocommerce/src/Resources/views/layouts/blank/config/jsmodules.yml`
```diff
aliases:
  aligentbraintree/js/app/components/braintree-method-component$: aligentbraintree/js/app/components/braintree-method-component
  aligentbraintree/js/app/components/order-review-component$: aligentbraintree/js/app/components/order-review-component
- braintree-web-drop-in$: npmassets/braintree-web-drop-in
+ braintree-web-drop-in$: braintree-web-drop-in

dynamic-imports:
  aligentbraintree:
    - aligentbraintree/js/app/components/braintree-method-component
    - aligentbraintree/js/app/components/order-review-component
    - braintree-web-drop-in
```

**Comment by AdamJHall** [comment]
This issue has now been resolved in the 4.2 branch and will be tagged for release shortly
